site_name: Yaptide for developers
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

nav:
- Backend:
  - Overview: backend/index.md
- Frontend:
  - Overview: frontend/index.md
- Editing documentation: other/index.md

plugins:
- search
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- coverage:
    page_name: coverage
    html_report_dir: htmlcov
- render_swagger
- mkdocstrings:
    enable_inventory: true
    handlers:
      python:
        paths: [yaptide]
        options:
          show_if_no_docstring: true
          line_numbers: true
          inheritance_diagram: true
          separate_signature: true
          show_root_heading: true
          show_root_members_full_path: false

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
