site_name: Yaptide for developers
site_url: https://yaptide.github.io/for_developers
repo_url: https://github.com/yaptide/for_developers
repo_name: yaptide/for_developers
copyright: Copyright &copy; 2024 the Yaptide team

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

nav:
- Backend:
  - Overview: backend/index.md
  - For developers: backend/for_developers.md
  - Using docker: backend/using_docker.md
  - API: backend/swagger.md
  - Jobs and tasks: backend/states.md
  - Persistent storage: backend/persistency.md
  - Docker images on GHCR: backend/ghcr_packages.md
  - Test coverage: coverage.md
  - Code Reference: reference/
- Frontend:
  - Overview: frontend/index.md
  - For developers: frontend/for_developers.md
  - Examples: frontend/examples.md
  - Authentication: frontend/authentication.md 
  - Examples: frontend/examples.md
  - ThreeJs development: frontend/three_editor_development.md
- Converter:
  - Overview: converter/index.md
  - Readme: converter/readme.md
- Editing documentation: documentation/index.md

plugins:
- search
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- coverage:
    page_name: coverage
    html_report_dir: htmlcov
- render_swagger
- mkdocstrings:
    enable_inventory: true
    handlers:
      python:
        paths: [yaptide]
        options:
          show_if_no_docstring: true
          line_numbers: true
          inheritance_diagram: true
          separate_signature: true
          show_root_heading: true
          show_root_members_full_path: false

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
