name: Deploy documentation content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'
      - name: Temporarily rename pyproject from for_developers
        run: |
          mv pyproject.toml pyproject_docs.toml
          mv poetry.lock poetry_docs.lock
      - name: Clone backend repo
        uses: actions/checkout@v4
        with:
          repository: 'yaptide/yaptide'
          path: 'backend_repository'
          sparse-checkout: |
            yaptide/
            tests/
            yaptide_tester/
            pyproject.toml
            poetry.lock
            pytest.ini
      - name: move yaptide and tests to root dir wiht dependencies specification
        run: |
          mv backend_repository/yaptide .
          mv backend_repository/tests .
          mv backend_repository/yaptide_tester .
          mv backend_repository/pyproject.toml .
          mv backend_repository/poetry.lock .
          mv backend_repository/pytest.ini .
      - name: Update pip and install poetry
        run: |
          python3 -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies for production
        run: poetry install --only main
      - name: Install dependencies for tests
        run: poetry install --only test
      - name: Run tests
        uses: nick-fields/retry@v3
        # env:
        #   S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
        #   S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        #   S3_ENCRYPTION_PASSWORD: ${{ secrets.S3_ENCRYPTION_PASSWORD }}
        #   S3_ENCRYPTION_SALT: ${{ secrets.S3_ENCRYPTION_SALT }}
        #   S3_SHIELDHIT_BUCKET: ${{ vars.S3_LINUX_SHIELDHIT_BUCKET }}
        #   S3_SHIELDHIT_KEY: ${{ vars.S3_LINUX_SHIELDHIT_KEY }}
        #   S3_FLUKA_BUCKET: ${{ vars.S3_FLUKA_BUCKET }}
        #   S3_FLUKA_KEY: ${{ vars.S3_FLUKA_KEY }}
        command: poetry run pytest --cov-report html:htmlcov --cov=yaptide
      - name: Remove unused pyproject and dependencies
        run: | 
          rm pyproject.toml
          rm poetry.lock
      - name: Bring back original dependencies
        run: | 
          mv pyproject_docs.toml pyproject.toml
          mv poetry_docs.lock poetry.lock
      - name: Install dependencies for documentation
        run: |
          poetry lock
          poetry install
      - name: Build site
        run: mkdocs build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact if on main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'
      - name: Deploy to GitHub Pages if on main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
